name: CI
on: [push, pull_request]

jobs:
  build-test-publish:
    # For tag pushes, we want to assure only the tag event triggers CI,
    # not the accompanying commit:
    if: ${{ ! startsWith(toJSON(github.event.head_commit.message), 'Bump ') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Add miniconda to PATH
        run: echo "::add-path::${HOME}/miniconda3/bin"

      - name: Setup conda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
            --no-verbose -O miniconda.sh
          bash miniconda.sh -b
          conda config --set always_yes yes --set changeps1 no
          conda install -c conda-forge mamba
          mamba update conda
          conda config --add channels defaults --add channels vladsaveliev \
            --add channels bioconda --add channels conda-forge
          mamba install pip versionpy conda-build conda-verify anaconda-client

      - name: Build package
        run: mamba build conda/$(basename $GITHUB_REPOSITORY)

      - name: Install
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: mamba install --use-local $(basename $GITHUB_REPOSITORY)

      - name: Test
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          python -c "from versionpy import get_version, increment_version"
          bump --help

      - name: Upload to anaconda
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} \
            upload ${HOME}/miniconda3/conda-bld/**/*.tar.bz2

      - name: Publish to Pypi
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          pip install setuptools wheel twine
          python setup.py sdist bdist_wheel
          twine upload dist/*
